dig_dpb_environ_commands_read = [
    "READ DIG0 GWVER",
    "READ DIG0 SWVER",
    "READ DIG0 BDSTATUS",
    "READ DIG0 BDCONTROL",
    "READ DIG0 UPTIME",
    "READ DIG0 DAQCLOCK",
    "READ DIG0 TLNLOCK",
    "READ DIG0 OUI",
    "READ DIG0 EID",
    "READ DIG0 RMONT",
    "READ DIG0 RMONMUX",
    "READ DIG0 RMONRST",
    "READ DIG0 3V3A",
    "READ DIG0 12VA",
    "READ DIG0 I12V",
    "READ DIG0 5V0A",
    "READ DIG0 5V0F",
    "READ DIG0 C12V",
    "READ DIG0 I5VF",
    "READ DIG0 I3V3A",
    "READ DIG0 I12VA",
    "READ DIG0 TPWR",
    "READ DIG0 TFE",
    "READ DIG0 TFPGA",
    "READ DIG0 TEMP",
    "READ DIG0 RELHUM",
    "READ DIG0 PRESS"
]

dig_dpb_environ_commands_set = [
    "SET DIG0 DISCTRES ALL 4020",
    "SET DIG0 INTTIME ALL 15",
    "SET DIG0 DEADTIME ALL 1",
    "SET DIG0 FESTATUS ALL ON",
    "SET DIG0 FESTATUS ALL OFF",
    "SET DIG0 DAQSTATUS ALL ON",
    "SET DIG0 DAQSTATUS ALL OFF",
    "SET DIG0 TDCRST",
    "SET DIG0 AURORARST",
    "SET DIG0 CLOCK DPB",
    "SET DIG0 RMONT 100",
    "SET DIG0 RMONRUN"
]

dig_dpb_channel_commands_read = [
    "READ DIG0 DISCTRES 0", "READ DIG0 DISCTRES 1", "READ DIG0 DISCTRES 2",
    "READ DIG0 DISCTRES 3", "READ DIG0 DISCTRES 4", "READ DIG0 DISCTRES 5",
    "READ DIG0 DISCTRES 6", "READ DIG0 DISCTRES 7", "READ DIG0 DISCTRES 8",
    "READ DIG0 DISCTRES 9", "READ DIG0 DISCTRES 10", "READ DIG0 DISCTRES 11",
    
    "READ DIG0 INTTIME 0", "READ DIG0 INTTIME 1", "READ DIG0 INTTIME 2",
    "READ DIG0 INTTIME 3", "READ DIG0 INTTIME 4", "READ DIG0 INTTIME 5",
    "READ DIG0 INTTIME 6", "READ DIG0 INTTIME 7", "READ DIG0 INTTIME 8",
    "READ DIG0 INTTIME 9", "READ DIG0 INTTIME 10", "READ DIG0 INTTIME 11",
    
    "READ DIG0 DEADTIME 0", "READ DIG0 DEADTIME 1", "READ DIG0 DEADTIME 2",
    "READ DIG0 DEADTIME 3", "READ DIG0 DEADTIME 4", "READ DIG0 DEADTIME 5",
    "READ DIG0 DEADTIME 6", "READ DIG0 DEADTIME 7", "READ DIG0 DEADTIME 8",
    "READ DIG0 DEADTIME 9", "READ DIG0 DEADTIME 10", "READ DIG0 DEADTIME 11",
    
    "READ DIG0 STATUS 0", "READ DIG0 STATUS 1", "READ DIG0 STATUS 2",
    "READ DIG0 STATUS 3", "READ DIG0 STATUS 4", "READ DIG0 STATUS 5",
    "READ DIG0 STATUS 6", "READ DIG0 STATUS 7", "READ DIG0 STATUS 8",
    "READ DIG0 STATUS 9", "READ DIG0 STATUS 10", "READ DIG0 STATUS 11",
    
    "READ DIG0 CHCONTROL 0", "READ DIG0 CHCONTROL 1", "READ DIG0 CHCONTROL 2",
    "READ DIG0 CHCONTROL 3", "READ DIG0 CHCONTROL 4", "READ DIG0 CHCONTROL 5",
    "READ DIG0 CHCONTROL 6", "READ DIG0 CHCONTROL 7", "READ DIG0 CHCONTROL 8",
    "READ DIG0 CHCONTROL 9", "READ DIG0 CHCONTROL 10", "READ DIG0 CHCONTROL 11",
    
    "READ DIG0 PEDTYPE 0", "READ DIG0 PEDTYPE 1", "READ DIG0 PEDTYPE 2",
    "READ DIG0 PEDTYPE 3", "READ DIG0 PEDTYPE 4", "READ DIG0 PEDTYPE 5",
    "READ DIG0 PEDTYPE 6", "READ DIG0 PEDTYPE 7", "READ DIG0 PEDTYPE 8",
    "READ DIG0 PEDTYPE 9", "READ DIG0 PEDTYPE 10", "READ DIG0 PEDTYPE 11",
    
    "READ DIG0 RMONADC 0", "READ DIG0 RMONADC 1", "READ DIG0 RMONADC 2",
    "READ DIG0 RMONADC 3", "READ DIG0 RMONADC 4", "READ DIG0 RMONADC 5",
    "READ DIG0 RMONADC 6", "READ DIG0 RMONADC 7", "READ DIG0 RMONADC 8",
    "READ DIG0 RMONADC 9", "READ DIG0 RMONADC 10", "READ DIG0 RMONADC 11",
    
    "READ DIG0 RMONTDC 0", "READ DIG0 RMONTDC 1", "READ DIG0 RMONTDC 2",
    "READ DIG0 RMONTDC 3", "READ DIG0 RMONTDC 4", "READ DIG0 RMONTDC 5",
    "READ DIG0 RMONTDC 6", "READ DIG0 RMONTDC 7", "READ DIG0 RMONTDC 8",
    "READ DIG0 RMONTDC 9", "READ DIG0 RMONTDC 10", "READ DIG0 RMONTDC 11",
    
    "READ DIG0 RMONFMT 0", "READ DIG0 RMONFMT 1", "READ DIG0 RMONFMT 2",
    "READ DIG0 RMONFMT 3", "READ DIG0 RMONFMT 4", "READ DIG0 RMONFMT 5",
    "READ DIG0 RMONFMT 6", "READ DIG0 RMONFMT 7", "READ DIG0 RMONFMT 8",
    "READ DIG0 RMONFMT 9", "READ DIG0 RMONFMT 10", "READ DIG0 RMONFMT 11"
]

dig_dpb_channel_commands_set = [
    "SET DIG0 DISCTRES 0 4020", "SET DIG0 DISCTRES 1 4020", "SET DIG0 DISCTRES 2 4020",
    "SET DIG0 DISCTRES 3 4020", "SET DIG0 DISCTRES 4 4020", "SET DIG0 DISCTRES 5 4020",
    "SET DIG0 DISCTRES 6 4020", "SET DIG0 DISCTRES 7 4020", "SET DIG0 DISCTRES 8 4020",
    "SET DIG0 DISCTRES 9 4020", "SET DIG0 DISCTRES 10 4020", "SET DIG0 DISCTRES 11 4020",
    
    "SET DIG0 INTTIME 0 15", "SET DIG0 INTTIME 1 15", "SET DIG0 INTTIME 2 15",
    "SET DIG0 INTTIME 3 15", "SET DIG0 INTTIME 4 15", "SET DIG0 INTTIME 5 15",
    "SET DIG0 INTTIME 6 15", "SET DIG0 INTTIME 7 15", "SET DIG0 INTTIME 8 15",
    "SET DIG0 INTTIME 9 15", "SET DIG0 INTTIME 10 15", "SET DIG0 INTTIME 11 15",
    
    "SET DIG0 DEADTIME 0 1", "SET DIG0 DEADTIME 1 1", "SET DIG0 DEADTIME 2 1",
    "SET DIG0 DEADTIME 3 1", "SET DIG0 DEADTIME 4 1", "SET DIG0 DEADTIME 5 1",
    "SET DIG0 DEADTIME 6 1", "SET DIG0 DEADTIME 7 0", "SET DIG0 DEADTIME 8 0",
    "SET DIG0 DEADTIME 9 1", "SET DIG0 DEADTIME 10 1", "SET DIG0 DEADTIME 11 1",
    
    "SET DIG0 CALIB 0 ON", "SET DIG0 CALIB 1 ON", "SET DIG0 CALIB 2 ON",
    "SET DIG0 CALIB 3 ON", "SET DIG0 CALIB 4 ON", "SET DIG0 CALIB 5 ON",
    "SET DIG0 CALIB 6 ON", "SET DIG0 CALIB 7 ON", "SET DIG0 CALIB 8 ON",
    "SET DIG0 CALIB 9 ON", "SET DIG0 CALIB 10 ON", "SET DIG0 CALIB 11 ON",
    
    "SET DIG0 CALIB 0 OFF", "SET DIG0 CALIB 1 OFF", "SET DIG0 CALIB 2 OFF",
    "SET DIG0 CALIB 3 OFF", "SET DIG0 CALIB 4 OFF", "SET DIG0 CALIB 5 OFF",
    "SET DIG0 CALIB 6 OFF", "SET DIG0 CALIB 7 OFF", "SET DIG0 CALIB 8 OFF",
    "SET DIG0 CALIB 9 OFF", "SET DIG0 CALIB 10 OFF", "SET DIG0 CALIB 11 OFF",
    
    "SET DIG0 FESTATUS 0 ON", "SET DIG0 FESTATUS 1 ON", "SET DIG0 FESTATUS 2 ON",
    "SET DIG0 FESTATUS 3 ON", "SET DIG0 FESTATUS 4 ON", "SET DIG0 FESTATUS 5 ON",
    "SET DIG0 FESTATUS 6 ON", "SET DIG0 FESTATUS 7 ON", "SET DIG0 FESTATUS 8 ON",
    "SET DIG0 FESTATUS 9 ON", "SET DIG0 FESTATUS 10 ON", "SET DIG0 FESTATUS 11 ON",
    
    "SET DIG0 FESTATUS 0 OFF", "SET DIG0 FESTATUS 1 OFF", "SET DIG0 FESTATUS 2 OFF",
    "SET DIG0 FESTATUS 3 OFF", "SET DIG0 FESTATUS 4 OFF", "SET DIG0 FESTATUS 5 OFF",
    "SET DIG0 FESTATUS 6 OFF", "SET DIG0 FESTATUS 7 OFF", "SET DIG0 FESTATUS 8 OFF",
    "SET DIG0 FESTATUS 9 OFF", "SET DIG0 FESTATUS 10 OFF", "SET DIG0 FESTATUS 11 OFF",
    
    "SET DIG0 DAQSTATUS 0 ON", "SET DIG0 DAQSTATUS 1 ON", "SET DIG0 DAQSTATUS 2 ON",
    "SET DIG0 DAQSTATUS 3 ON", "SET DIG0 DAQSTATUS 4 ON", "SET DIG0 DAQSTATUS 5 ON",
    "SET DIG0 DAQSTATUS 6 ON", "SET DIG0 DAQSTATUS 7 ON", "SET DIG0 DAQSTATUS 8 ON",
    "SET DIG0 DAQSTATUS 9 ON", "SET DIG0 DAQSTATUS 10 ON", "SET DIG0 DAQSTATUS 11 ON",
    
    "SET DIG0 DAQSTATUS 0 OFF", "SET DIG0 DAQSTATUS 1 OFF", "SET DIG0 DAQSTATUS 2 OFF",
    "SET DIG0 DAQSTATUS 3 OFF", "SET DIG0 DAQSTATUS 4 OFF", "SET DIG0 DAQSTATUS 5 OFF",
    "SET DIG0 DAQSTATUS 6 OFF", "SET DIG0 DAQSTATUS 7 OFF", "SET DIG0 DAQSTATUS 8 OFF",
    "SET DIG0 DAQSTATUS 9 OFF", "SET DIG0 DAQSTATUS 10 OFF", "SET DIG0 DAQSTATUS 11 OFF",
    
    "SET DIG0 PEDTYPE 0 0", "SET DIG0 PEDTYPE 1 0", "SET DIG0 PEDTYPE 2 0",
    "SET DIG0 PEDTYPE 3 0", "SET DIG0 PEDTYPE 4 0", "SET DIG0 PEDTYPE 5 0",
    "SET DIG0 PEDTYPE 6 1", "SET DIG0 PEDTYPE 7 1", "SET DIG0 PEDTYPE 8 1",
    "SET DIG0 PEDTYPE 9 1", "SET DIG0 PEDTYPE 10 1", "SET DIG0 PEDTYPE 11 1"
]
