hv_environ_read_commands = [
    "READ HV BDSNUM",
    "READ HV TEMP"
]

lv_environ_read_commands = [
    "READ LV BDSNUM",
    "READ LV TEMP",
    "READ LV BCMTEMP",
    "READ LV RELHUM",
    "READ LV PRESS",
    "READ LV WLEAK"
]

lv_channel_read_commands = [
    "READ LV STATUS 0",
    "READ LV STATUS 1",
    "READ LV STATUS 2",
    "READ LV STATUS 3",
    "READ LV STATUS 4",
    "READ LV STATUS 5",
    "READ LV STATUS 6",
    "READ LV STATUS 7",
    "READ LV VOLT 0",
    "READ LV VOLT 1",
    "READ LV VOLT 2",
    "READ LV VOLT 3",
    "READ LV VOLT 4",
    "READ LV VOLT 5",
    "READ LV VOLT 6",
    "READ LV VOLT 7",
    "READ LV CURR 0",
    "READ LV CURR 1",
    "READ LV CURR 2",
    "READ LV CURR 3",
    "READ LV CURR 4",
    "READ LV CURR 5",
    "READ LV CURR 6",
    "READ LV CURR 7",
]

hv_channel_read_commands = [
        "READ HV STATUS 0", "READ HV STATUS 1", "READ HV STATUS 2", "READ HV STATUS 3", "READ HV STATUS 4", 
    "READ HV STATUS 5", "READ HV STATUS 6", "READ HV STATUS 7", "READ HV STATUS 8", "READ HV STATUS 9", 
    "READ HV STATUS 10", "READ HV STATUS 11", "READ HV STATUS 12", "READ HV STATUS 13", "READ HV STATUS 14", 
    "READ HV STATUS 15", "READ HV STATUS 16", "READ HV STATUS 17", "READ HV STATUS 18", "READ HV STATUS 19", 
    "READ HV STATUS 20", "READ HV STATUS 21", "READ HV STATUS 22", "READ HV STATUS 23",
    
    "READ HV VOLT 0", "READ HV VOLT 1", "READ HV VOLT 2", "READ HV VOLT 3", "READ HV VOLT 4", 
    "READ HV VOLT 5", "READ HV VOLT 6", "READ HV VOLT 7", "READ HV VOLT 8", "READ HV VOLT 9", 
    "READ HV VOLT 10", "READ HV VOLT 11", "READ HV VOLT 12", "READ HV VOLT 13", "READ HV VOLT 14", 
    "READ HV VOLT 15", "READ HV VOLT 16", "READ HV VOLT 17", "READ HV VOLT 18", "READ HV VOLT 19", 
    "READ HV VOLT 20", "READ HV VOLT 21", "READ HV VOLT 22", "READ HV VOLT 23",
    
    "READ HV CURR 0", "READ HV CURR 1", "READ HV CURR 2", "READ HV CURR 3", "READ HV CURR 4", 
    "READ HV CURR 5", "READ HV CURR 6", "READ HV CURR 7", "READ HV CURR 8", "READ HV CURR 9", 
    "READ HV CURR 10", "READ HV CURR 11", "READ HV CURR 12", "READ HV CURR 13", "READ HV CURR 14", 
    "READ HV CURR 15", "READ HV CURR 16", "READ HV CURR 17", "READ HV CURR 18", "READ HV CURR 19", 
    "READ HV CURR 20", "READ HV CURR 21", "READ HV CURR 22", "READ HV CURR 23",
    
    "READ HV CHANTEMP 0", "READ HV CHANTEMP 1", "READ HV CHANTEMP 2", "READ HV CHANTEMP 3", "READ HV CHANTEMP 4", 
    "READ HV CHANTEMP 5", "READ HV CHANTEMP 6", "READ HV CHANTEMP 7", "READ HV CHANTEMP 8", "READ HV CHANTEMP 9", 
    "READ HV CHANTEMP 10", "READ HV CHANTEMP 11", "READ HV CHANTEMP 12", "READ HV CHANTEMP 13", "READ HV CHANTEMP 14", 
    "READ HV CHANTEMP 15", "READ HV CHANTEMP 16", "READ HV CHANTEMP 17", "READ HV CHANTEMP 18", "READ HV CHANTEMP 19", 
    "READ HV CHANTEMP 20", "READ HV CHANTEMP 21", "READ HV CHANTEMP 22", "READ HV CHANTEMP 23",
    
    "READ HV RAMPUP 0", "READ HV RAMPUP 1", "READ HV RAMPUP 2", "READ HV RAMPUP 3", "READ HV RAMPUP 4", 
    "READ HV RAMPUP 5", "READ HV RAMPUP 6", "READ HV RAMPUP 7", "READ HV RAMPUP 8", "READ HV RAMPUP 9", 
    "READ HV RAMPUP 10", "READ HV RAMPUP 11", "READ HV RAMPUP 12", "READ HV RAMPUP 13", "READ HV RAMPUP 14", 
    "READ HV RAMPUP 15", "READ HV RAMPUP 16", "READ HV RAMPUP 17", "READ HV RAMPUP 18", "READ HV RAMPUP 19", 
    "READ HV RAMPUP 20", "READ HV RAMPUP 21", "READ HV RAMPUP 22", "READ HV RAMPUP 23",
    
    "READ HV RAMPDOWN 0", "READ HV RAMPDOWN 1", "READ HV RAMPDOWN 2", "READ HV RAMPDOWN 3", "READ HV RAMPDOWN 4", 
    "READ HV RAMPDOWN 5", "READ HV RAMPDOWN 6", "READ HV RAMPDOWN 7", "READ HV RAMPDOWN 8", "READ HV RAMPDOWN 9", 
    "READ HV RAMPDOWN 10", "READ HV RAMPDOWN 11", "READ HV RAMPDOWN 12", "READ HV RAMPDOWN 13", "READ HV RAMPDOWN 14", 
    "READ HV RAMPDOWN 15", "READ HV RAMPDOWN 16", "READ HV RAMPDOWN 17", "READ HV RAMPDOWN 18", "READ HV RAMPDOWN 19", 
    "READ HV RAMPDOWN 20", "READ HV RAMPDOWN 21", "READ HV RAMPDOWN 22", "READ HV RAMPDOWN 23",
    
    "READ HV TRIP 0", "READ HV TRIP 1", "READ HV TRIP 2", "READ HV TRIP 3", "READ HV TRIP 4", 
    "READ HV TRIP 5", "READ HV TRIP 6", "READ HV TRIP 7", "READ HV TRIP 8", "READ HV TRIP 9", 
    "READ HV TRIP 10", "READ HV TRIP 11", "READ HV TRIP 12", "READ HV TRIP 13", "READ HV TRIP 14", 
    "READ HV TRIP 15", "READ HV TRIP 16", "READ HV TRIP 17", "READ HV TRIP 18", "READ HV TRIP 19", 
    "READ HV TRIP 20", "READ HV TRIP 21", "READ HV TRIP 22", "READ HV TRIP 23",
    
    "READ HV CHANERR 0", "READ HV CHANERR 1", "READ HV CHANERR 2", "READ HV CHANERR 3", "READ HV CHANERR 4", 
    "READ HV CHANERR 5", "READ HV CHANERR 6", "READ HV CHANERR 7", "READ HV CHANERR 8", "READ HV CHANERR 9", 
    "READ HV CHANERR 10", "READ HV CHANERR 11", "READ HV CHANERR 12", "READ HV CHANERR 13", "READ HV CHANERR 14", 
    "READ HV CHANERR 15", "READ HV CHANERR 16", "READ HV CHANERR 17", "READ HV CHANERR 18", "READ HV CHANERR 19", 
    "READ HV CHANERR 20", "READ HV CHANERR 21", "READ HV CHANERR 22", "READ HV CHANERR 23",
    
    "READ HV SDVOLT 0", "READ HV SDVOLT 1", "READ HV SDVOLT 2", "READ HV SDVOLT 3", "READ HV SDVOLT 4", 
    "READ HV SDVOLT 5", "READ HV SDVOLT 6", "READ HV SDVOLT 7", "READ HV SDVOLT 8", "READ HV SDVOLT 9", 
    "READ HV SDVOLT 10", "READ HV SDVOLT 11", "READ HV SDVOLT 12", "READ HV SDVOLT 13", "READ HV SDVOLT 14", 
    "READ HV SDVOLT 15", "READ HV SDVOLT 16", "READ HV SDVOLT 17", "READ HV SDVOLT 18", "READ HV SDVOLT 19", 
    "READ HV SDVOLT 20", "READ HV SDVOLT 21", "READ HV SDVOLT 22", "READ HV SDVOLT 23",
    
    "READ HV SDCURR 0", "READ HV SDCURR 1", "READ HV SDCURR 2", "READ HV SDCURR 3", "READ HV SDCURR 4", 
    "READ HV SDCURR 5", "READ HV SDCURR 6", "READ HV SDCURR 7", "READ HV SDCURR 8", "READ HV SDCURR 9", 
    "READ HV SDCURR 10", "READ HV SDCURR 11", "READ HV SDCURR 12", "READ HV SDCURR 13", "READ HV SDCURR 14", 
    "READ HV SDCURR 15", "READ HV SDCURR 16", "READ HV SDCURR 17", "READ HV SDCURR 18", "READ HV SDCURR 19", 
    "READ HV SDCURR 20", "READ HV SDCURR 21", "READ HV SDCURR 22", "READ HV SDCURR 23"
]


lv_channel_set_commands = [
    "SET LV STATUS 0 ON", "SET LV STATUS 1 ON", "SET LV STATUS 2 ON", "SET LV STATUS 3 ON", 
    "SET LV STATUS 4 ON", "SET LV STATUS 5 ON", "SET LV STATUS 6 ON", "SET LV STATUS 7 ON",
    "SET LV VOLT 0 15", "SET LV VOLT 1 15", "SET LV VOLT 2 15", "SET LV VOLT 3 15", 
    "SET LV VOLT 4 15", "SET LV VOLT 5 15", "SET LV VOLT 6 15", "SET LV VOLT 7 15",
    "SET LV CURR 0 2000", "SET LV CURR 1 2000", "SET LV CURR 2 2000", "SET LV CURR 3 2000", 
    "SET LV CURR 4 2000", "SET LV CURR 5 2000", "SET LV CURR 6 2000", "SET LV CURR 7 2000",
    "SET LV CPU MAIN ON", "SET LV CPU MAIN OFF", "SET LV CPU BACKUP ON", "SET LV CPU BACKUP OFF",
]

hv_channel_set_commands = [
    "SET HV STATUS 0 OFF", "SET HV STATUS 1 OFF", "SET HV STATUS 2 OFF", "SET HV STATUS 3 OFF", 
    "SET HV STATUS 4 OFF", "SET HV STATUS 5 OFF", "SET HV STATUS 6 OFF", "SET HV STATUS 7 OFF",
    "SET HV STATUS 8 OFF", "SET HV STATUS 9 OFF", "SET HV STATUS 10 OFF", "SET HV STATUS 11 OFF", 
    "SET HV STATUS 12 OFF", "SET HV STATUS 13 OFF", "SET HV STATUS 14 OFF", "SET HV STATUS 15 OFF", 
    "SET HV STATUS 16 OFF", "SET HV STATUS 17 OFF", "SET HV STATUS 18 OFF", "SET HV STATUS 19 OFF", 
    "SET HV STATUS 20 OFF", "SET HV STATUS 21 OFF", "SET HV STATUS 22 OFF", "SET HV STATUS 23 OFF",
    
    "SET HV VOLT 0 2500", "SET HV VOLT 1 2500", "SET HV VOLT 2 2500", "SET HV VOLT 3 2500", 
    "SET HV VOLT 4 2500", "SET HV VOLT 5 2500", "SET HV VOLT 6 2500", "SET HV VOLT 7 2500",
    "SET HV VOLT 8 2500", "SET HV VOLT 9 2500", "SET HV VOLT 10 2500", "SET HV VOLT 11 2500", 
    "SET HV VOLT 12 2500", "SET HV VOLT 13 2500", "SET HV VOLT 14 2500", "SET HV VOLT 15 2500", 
    "SET HV VOLT 16 2500", "SET HV VOLT 17 2500", "SET HV VOLT 18 2500", "SET HV VOLT 19 2500", 
    "SET HV VOLT 20 2500", "SET HV VOLT 21 2500", "SET HV VOLT 22 2500", "SET HV VOLT 23 2500",
    
    "SET HV CURR 0 500", "SET HV CURR 1 500", "SET HV CURR 2 500", "SET HV CURR 3 500", 
    "SET HV CURR 4 500", "SET HV CURR 5 500", "SET HV CURR 6 500", "SET HV CURR 7 500",
    "SET HV CURR 8 500", "SET HV CURR 9 500", "SET HV CURR 10 500", "SET HV CURR 11 500", 
    "SET HV CURR 12 500", "SET HV CURR 13 500", "SET HV CURR 14 500", "SET HV CURR 15 500", 
    "SET HV CURR 16 500", "SET HV CURR 17 500", "SET HV CURR 18 500", "SET HV CURR 19 500", 
    "SET HV CURR 20 500", "SET HV CURR 21 500", "SET HV CURR 22 500", "SET HV CURR 23 500",
    
    "SET HV RAMPUP 0 50", "SET HV RAMPUP 1 50", "SET HV RAMPUP 2 50", "SET HV RAMPUP 3 50", 
    "SET HV RAMPUP 4 50", "SET HV RAMPUP 5 50", "SET HV RAMPUP 6 50", "SET HV RAMPUP 7 50",
    "SET HV RAMPUP 8 50", "SET HV RAMPUP 9 50", "SET HV RAMPUP 10 50", "SET HV RAMPUP 11 50", 
    "SET HV RAMPUP 12 50", "SET HV RAMPUP 13 50", "SET HV RAMPUP 14 50", "SET HV RAMPUP 15 50", 
    "SET HV RAMPUP 16 50", "SET HV RAMPUP 17 50", "SET HV RAMPUP 18 50", "SET HV RAMPUP 19 50", 
    "SET HV RAMPUP 20 50", "SET HV RAMPUP 21 50", "SET HV RAMPUP 22 50", "SET HV RAMPUP 23 50",
    
    "SET HV RAMPDOWN 0 50", "SET HV RAMPDOWN 1 50", "SET HV RAMPDOWN 2 50", "SET HV RAMPDOWN 3 50", 
    "SET HV RAMPDOWN 4 50", "SET HV RAMPDOWN 5 50", "SET HV RAMPDOWN 6 50", "SET HV RAMPDOWN 7 50",
    "SET HV RAMPDOWN 8 50", "SET HV RAMPDOWN 9 50", "SET HV RAMPDOWN 10 50", "SET HV RAMPDOWN 11 50", 
    "SET HV RAMPDOWN 12 50", "SET HV RAMPDOWN 13 50", "SET HV RAMPDOWN 14 50", "SET HV RAMPDOWN 15 50", 
    "SET HV RAMPDOWN 16 50", "SET HV RAMPDOWN 17 50", "SET HV RAMPDOWN 18 50", "SET HV RAMPDOWN 19 50", 
    "SET HV RAMPDOWN 20 50", "SET HV RAMPDOWN 21 50", "SET HV RAMPDOWN 22 50", "SET HV RAMPDOWN 23 50",
    
    "SET HV TRIP 0", "SET HV TRIP 1", "SET HV TRIP 2", "SET HV TRIP 3", 
    "SET HV TRIP 4", "SET HV TRIP 5", "SET HV TRIP 6", "SET HV TRIP 7",
    "SET HV TRIP 8", "SET HV TRIP 9", "SET HV TRIP 10", "SET HV TRIP 11", 
    "SET HV TRIP 12", "SET HV TRIP 13", "SET HV TRIP 14", "SET HV TRIP 15", 
    "SET HV TRIP 16", "SET HV TRIP 17", "SET HV TRIP 18", "SET HV TRIP 19", 
    "SET HV TRIP 20", "SET HV TRIP 21", "SET HV TRIP 22", "SET HV TRIP 23"
]
