.TH "constants.h" 3 "Version 1.0.0" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBwrapper\fP"
.br
.RI "Shared Memory content\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINA3221_NUM_CHAN\fP   3"
.br
.ti -1c
.RI "#define \fBAMS_TEMP_NUM_CHAN\fP   3"
.br
.ti -1c
.RI "#define \fBAMS_VOLT_NUM_CHAN\fP   21"
.br
.ti -1c
.RI "#define \fBEINCMD\fP   1"
.br
.RI "Error command not valid\&. "
.ti -1c
.RI "#define \fBERRSET\fP   2"
.br
.RI "Error SET commnad not successful\&. "
.ti -1c
.RI "#define \fBERRREAD\fP   3"
.br
.RI "Error READ command not successful\&. "
.ti -1c
.RI "#define \fBGPIO_PINS_SIZE\fP   22"
.br
.RI "Number of GPIO pins used\&. "
.ti -1c
.RI "#define \fBDIG0_MAIN_AURORA_LINK\fP   40"
.br
.RI "GPIO pins definition\&. "
.ti -1c
.RI "#define \fBDIG0_BACKUP_AURORA_LINK\fP   41"
.br
.ti -1c
.RI "#define \fBDIG1_MAIN_AURORA_LINK\fP   42"
.br
.ti -1c
.RI "#define \fBDIG1_BACKUP_AURORA_LINK\fP   43"
.br
.ti -1c
.RI "#define \fBSFP0_PWR_ENA\fP   0"
.br
.ti -1c
.RI "#define \fBSFP1_PWR_ENA\fP   1"
.br
.ti -1c
.RI "#define \fBSFP2_PWR_ENA\fP   2"
.br
.ti -1c
.RI "#define \fBSFP3_PWR_ENA\fP   3"
.br
.ti -1c
.RI "#define \fBSFP4_PWR_ENA\fP   4"
.br
.ti -1c
.RI "#define \fBSFP5_PWR_ENA\fP   5"
.br
.ti -1c
.RI "#define \fBSFP0_TX_DIS\fP   6"
.br
.ti -1c
.RI "#define \fBSFP1_TX_DIS\fP   7"
.br
.ti -1c
.RI "#define \fBSFP2_TX_DIS\fP   8"
.br
.ti -1c
.RI "#define \fBSFP3_TX_DIS\fP   9"
.br
.ti -1c
.RI "#define \fBSFP4_TX_DIS\fP   10"
.br
.ti -1c
.RI "#define \fBSFP5_TX_DIS\fP   11"
.br
.ti -1c
.RI "#define \fBSFP0_RX_LOS\fP   14"
.br
.ti -1c
.RI "#define \fBSFP1_RX_LOS\fP   18"
.br
.ti -1c
.RI "#define \fBSFP2_RX_LOS\fP   22"
.br
.ti -1c
.RI "#define \fBSFP3_RX_LOS\fP   26"
.br
.ti -1c
.RI "#define \fBSFP4_RX_LOS\fP   30"
.br
.ti -1c
.RI "#define \fBSFP5_RX_LOS\fP   34"
.br
.ti -1c
.RI "#define \fBMCP9844_TEMP_UPPER_LIM_REG\fP   0x2"
.br
.ti -1c
.RI "#define \fBMCP9844_TEMP_LOWER_LIM_REG\fP   0x3"
.br
.ti -1c
.RI "#define \fBMCP9844_TEMP_CRIT_LIM_REG\fP   0x4"
.br
.ti -1c
.RI "#define \fBMCP9844_TEMP_UPPER_LIM\fP   0x0"
.br
.ti -1c
.RI "#define \fBMCP9844_TEMP_LOWER_LIM\fP   0x1"
.br
.ti -1c
.RI "#define \fBMCP9844_TEMP_CRIT_LIM\fP   0x2"
.br
.ti -1c
.RI "#define \fBMCP9844_TEMP_REG\fP   0x5"
.br
.ti -1c
.RI "#define \fBMCP9844_RES_REG\fP   0x9"
.br
.ti -1c
.RI "#define \fBMCP9844_CONFIG_REG\fP   0x1"
.br
.ti -1c
.RI "#define \fBMCP9844_MANUF_ID_REG\fP   0x6"
.br
.ti -1c
.RI "#define \fBMCP9844_DEVICE_ID_REG\fP   0x7"
.br
.ti -1c
.RI "#define \fBSFP_MSB_TEMP_REG\fP   0x60"
.br
.ti -1c
.RI "#define \fBSFP_LSB_TEMP_REG\fP   0x61"
.br
.ti -1c
.RI "#define \fBSFP_MSB_VCC_REG\fP   0x62"
.br
.ti -1c
.RI "#define \fBSFP_LSB_VCC_REG\fP   0x63"
.br
.ti -1c
.RI "#define \fBSFP_MSB_TXBIAS_REG\fP   0x64"
.br
.ti -1c
.RI "#define \fBSFP_LSB_TXBIAS_REG\fP   0x65"
.br
.ti -1c
.RI "#define \fBSFP_MSB_TXPWR_REG\fP   0x66"
.br
.ti -1c
.RI "#define \fBSFP_LSB_TXPWR_REG\fP   0x67"
.br
.ti -1c
.RI "#define \fBSFP_MSB_RXPWR_REG\fP   0x68"
.br
.ti -1c
.RI "#define \fBSFP_LSB_RXPWR_REG\fP   0x69"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HTEMP_ALARM_REG\fP   0x0"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HTEMP_ALARM_REG\fP   0x1"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LTEMP_ALARM_REG\fP   0x2"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LTEMP_ALARM_REG\fP   0x3"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HVCC_ALARM_REG\fP   0x8"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HVCC_ALARM_REG\fP   0x9"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LVCC_ALARM_REG\fP   0xA"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LVCC_ALARM_REG\fP   0xB"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HTXBIAS_ALARM_REG\fP   0x10"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HTXBIAS_ALARM_REG\fP   0x11"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LTXBIAS_ALARM_REG\fP   0x12"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LTXBIAS_ALARM_REG\fP   0x13"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HTXPWR_ALARM_REG\fP   0x18"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HTXPWR_ALARM_REG\fP   0x19"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LTXPWR_ALARM_REG\fP   0x1A"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LTXPWR_ALARM_REG\fP   0x1B"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HRXPWR_ALARM_REG\fP   0x20"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HRXPWR_ALARM_REG\fP   0x21"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LRXPWR_ALARM_REG\fP   0x22"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LRXPWR_ALARM_REG\fP   0x23"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HTEMP_WARN_REG\fP   0x4"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HTEMP_WARN_REG\fP   0x5"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LTEMP_WARN_REG\fP   0x6"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LTEMP_WARN_REG\fP   0x7"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HVCC_WARN_REG\fP   0xC"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HVCC_WARN_REG\fP   0xD"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LVCC_WARN_REG\fP   0xE"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LVCC_WARN_REG\fP   0xF"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HTXBIAS_WARN_REG\fP   0x14"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HTXBIAS_WARN_REG\fP   0x15"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LTXBIAS_WARN_REG\fP   0x16"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LTXBIAS_WARN_REG\fP   0x17"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HTXPWR_WARN_REG\fP   0xC"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HTXPWR_WARN_REG\fP   0xD"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LTXPWR_WARN_REG\fP   0xE"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LTXPWR_WARN_REG\fP   0xF"
.br
.ti -1c
.RI "#define \fBSFP_MSB_HRXPWR_WARN_REG\fP   0x24"
.br
.ti -1c
.RI "#define \fBSFP_LSB_HRXPWR_WARN_REG\fP   0x25"
.br
.ti -1c
.RI "#define \fBSFP_MSB_LRXPWR_WARN_REG\fP   0x26"
.br
.ti -1c
.RI "#define \fBSFP_LSB_LRXPWR_WARN_REG\fP   0x27"
.br
.ti -1c
.RI "#define \fBSFP_PHYS_DEV\fP   0x0"
.br
.ti -1c
.RI "#define \fBSFP_FUNCT\fP   0x1"
.br
.ti -1c
.RI "#define \fBSFP_CHECKSUM2_A0\fP   0x40"
.br
.ti -1c
.RI "#define \fBSFP_STAT_REG\fP   0x6E"
.br
.ti -1c
.RI "#define \fBSFP_FLG1_REG\fP   0x70"
.br
.ti -1c
.RI "#define \fBSFP_FLG2_REG\fP   0x71"
.br
.ti -1c
.RI "#define \fBSFP_FLG3_REG\fP   0x74"
.br
.ti -1c
.RI "#define \fBSFP_FLG4_REG\fP   0x75"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_1_REG\fP   0x1"
.br
.ti -1c
.RI "#define \fBINA3221_BUS_VOLTAGE_1_REG\fP   0x2"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_2_REG\fP   0x3"
.br
.ti -1c
.RI "#define \fBINA3221_BUS_VOLTAGE_2_REG\fP   0x4"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_3_REG\fP   0x5"
.br
.ti -1c
.RI "#define \fBINA3221_BUS_VOLTAGE_3_REG\fP   0x6"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_CRIT1_REG\fP   0x7"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_WARN1_REG\fP   0x8"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_CRIT2_REG\fP   0x9"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_WARN2_REG\fP   0xA"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_CRIT3_REG\fP   0xB"
.br
.ti -1c
.RI "#define \fBINA3221_SHUNT_VOLTAGE_WARN3_REG\fP   0xC"
.br
.ti -1c
.RI "#define \fBINA3221_CH1\fP   0x0"
.br
.ti -1c
.RI "#define \fBINA3221_CH2\fP   0x1"
.br
.ti -1c
.RI "#define \fBINA3221_CH3\fP   0x2"
.br
.ti -1c
.RI "#define \fBINA3221_CONFIG_REG\fP   0x0"
.br
.ti -1c
.RI "#define \fBINA3221_MASK_ENA_REG\fP   0xF"
.br
.ti -1c
.RI "#define \fBINA3221_MANUF_ID_REG\fP   0xFE"
.br
.ti -1c
.RI "#define \fBINA3221_DIE_ID_REG\fP   0xFF"
.br
.ti -1c
.RI "#define \fBDEV_SFP0\fP   0x0"
.br
.ti -1c
.RI "#define \fBDEV_SFP1\fP   0x1"
.br
.ti -1c
.RI "#define \fBDEV_SFP2\fP   0x2"
.br
.ti -1c
.RI "#define \fBDEV_SFP3\fP   0x3"
.br
.ti -1c
.RI "#define \fBDEV_SFP4\fP   0x4"
.br
.ti -1c
.RI "#define \fBDEV_SFP5\fP   0x5"
.br
.ti -1c
.RI "#define \fBDEV_SFP0_2_VOLT\fP   0x0"
.br
.ti -1c
.RI "#define \fBDEV_SFP3_5_VOLT\fP   0x1"
.br
.ti -1c
.RI "#define \fBDEV_SOM_VOLT\fP   0x2"
.br
.ti -1c
.RI "#define \fBMONIT_THREAD_PERIOD\fP   5000000"
.br
.ti -1c
.RI "#define \fBALARMS_THREAD_PERIOD\fP   100"
.br
.ti -1c
.RI "#define \fBAMS_ALARMS_THREAD_PERIOD\fP   100"
.br
.ti -1c
.RI "#define \fBCOMMAND_THREAD_PERIOD\fP   50"
.br
.ti -1c
.RI "#define \fBMEMORY_KEY\fP   7890"
.br
.RI "Shared Memory key\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBeth0_flag\fP = 1"
.br
.ti -1c
.RI "int \fBeth1_flag\fP = 1"
.br
.ti -1c
.RI "int \fBdig0_main_flag\fP = 1"
.br
.ti -1c
.RI "int \fBdig1_main_flag\fP = 1"
.br
.ti -1c
.RI "int \fBdig0_backup_flag\fP = 1"
.br
.ti -1c
.RI "int \fBdig1_backup_flag\fP = 1"
.br
.ti -1c
.RI "int \fBbreak_flag\fP = 0"
.br
.ti -1c
.RI "int \fBsfp0_connected\fP = 0"
.br
.ti -1c
.RI "int \fBsfp1_connected\fP = 0"
.br
.ti -1c
.RI "int \fBsfp2_connected\fP = 0"
.br
.ti -1c
.RI "int \fBsfp3_connected\fP = 0"
.br
.ti -1c
.RI "int \fBsfp4_connected\fP = 0"
.br
.ti -1c
.RI "int \fBsfp5_connected\fP = 0"
.br
.ti -1c
.RI "uint16_t \fBalarms_mask\fP [6] = {0,0,0,0,0,0}"
.br
.RI "Alarm mask\&. "
.ti -1c
.RI "uint8_t \fBstatus_mask\fP [6] = {0,0,0,0,0,0}"
.br
.RI "Status mask\&. "
.ti -1c
.RI "const int \fBGPIO_PINS\fP [\fBGPIO_PINS_SIZE\fP]"
.br
.RI "GPIO pins list\&. "
.ti -1c
.RI "int \fBGPIO_BASE_ADDRESS\fP = 0"
.br
.ti -1c
.RI "int \fBmemoryID\fP"
.br
.RI "Shared Memory ID\&. "
.ti -1c
.RI "struct \fBwrapper\fP * \fBmemory\fP"
.br
.RI "Shared Memory segment\&. "
.ti -1c
.RI "char * \fBams_channels\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ALARMS_THREAD_PERIOD   100"

.SS "#define AMS_ALARMS_THREAD_PERIOD   100"

.SS "#define AMS_TEMP_NUM_CHAN   3"

.SS "#define AMS_VOLT_NUM_CHAN   21"

.SS "#define COMMAND_THREAD_PERIOD   50"

.SS "#define DEV_SFP0   0x0"

.SS "#define DEV_SFP0_2_VOLT   0x0"

.SS "#define DEV_SFP1   0x1"

.SS "#define DEV_SFP2   0x2"

.SS "#define DEV_SFP3   0x3"

.SS "#define DEV_SFP3_5_VOLT   0x1"

.SS "#define DEV_SFP4   0x4"

.SS "#define DEV_SFP5   0x5"

.SS "#define DEV_SOM_VOLT   0x2"

.SS "#define INA3221_BUS_VOLTAGE_1_REG   0x2"

.SS "#define INA3221_BUS_VOLTAGE_2_REG   0x4"

.SS "#define INA3221_BUS_VOLTAGE_3_REG   0x6"

.SS "#define INA3221_CH1   0x0"

.SS "#define INA3221_CH2   0x1"

.SS "#define INA3221_CH3   0x2"

.SS "#define INA3221_CONFIG_REG   0x0"

.SS "#define INA3221_DIE_ID_REG   0xFF"

.SS "#define INA3221_MANUF_ID_REG   0xFE"

.SS "#define INA3221_MASK_ENA_REG   0xF"

.SS "#define INA3221_NUM_CHAN   3"

.SS "#define INA3221_SHUNT_VOLTAGE_1_REG   0x1"

.SS "#define INA3221_SHUNT_VOLTAGE_2_REG   0x3"

.SS "#define INA3221_SHUNT_VOLTAGE_3_REG   0x5"

.SS "#define INA3221_SHUNT_VOLTAGE_CRIT1_REG   0x7"

.SS "#define INA3221_SHUNT_VOLTAGE_CRIT2_REG   0x9"

.SS "#define INA3221_SHUNT_VOLTAGE_CRIT3_REG   0xB"

.SS "#define INA3221_SHUNT_VOLTAGE_WARN1_REG   0x8"

.SS "#define INA3221_SHUNT_VOLTAGE_WARN2_REG   0xA"

.SS "#define INA3221_SHUNT_VOLTAGE_WARN3_REG   0xC"

.SS "#define MCP9844_CONFIG_REG   0x1"

.SS "#define MCP9844_DEVICE_ID_REG   0x7"

.SS "#define MCP9844_MANUF_ID_REG   0x6"

.SS "#define MCP9844_RES_REG   0x9"

.SS "#define MCP9844_TEMP_CRIT_LIM   0x2"

.SS "#define MCP9844_TEMP_CRIT_LIM_REG   0x4"

.SS "#define MCP9844_TEMP_LOWER_LIM   0x1"

.SS "#define MCP9844_TEMP_LOWER_LIM_REG   0x3"

.SS "#define MCP9844_TEMP_REG   0x5"

.SS "#define MCP9844_TEMP_UPPER_LIM   0x0"

.SS "#define MCP9844_TEMP_UPPER_LIM_REG   0x2"

.SS "#define MONIT_THREAD_PERIOD   5000000"

.SS "#define SFP_CHECKSUM2_A0   0x40"

.SS "#define SFP_FLG1_REG   0x70"

.SS "#define SFP_FLG2_REG   0x71"

.SS "#define SFP_FLG3_REG   0x74"

.SS "#define SFP_FLG4_REG   0x75"

.SS "#define SFP_FUNCT   0x1"

.SS "#define SFP_LSB_HRXPWR_ALARM_REG   0x21"

.SS "#define SFP_LSB_HRXPWR_WARN_REG   0x25"

.SS "#define SFP_LSB_HTEMP_ALARM_REG   0x1"

.SS "#define SFP_LSB_HTEMP_WARN_REG   0x5"

.SS "#define SFP_LSB_HTXBIAS_ALARM_REG   0x11"

.SS "#define SFP_LSB_HTXBIAS_WARN_REG   0x15"

.SS "#define SFP_LSB_HTXPWR_ALARM_REG   0x19"

.SS "#define SFP_LSB_HTXPWR_WARN_REG   0xD"

.SS "#define SFP_LSB_HVCC_ALARM_REG   0x9"

.SS "#define SFP_LSB_HVCC_WARN_REG   0xD"

.SS "#define SFP_LSB_LRXPWR_ALARM_REG   0x23"

.SS "#define SFP_LSB_LRXPWR_WARN_REG   0x27"

.SS "#define SFP_LSB_LTEMP_ALARM_REG   0x3"

.SS "#define SFP_LSB_LTEMP_WARN_REG   0x7"

.SS "#define SFP_LSB_LTXBIAS_ALARM_REG   0x13"

.SS "#define SFP_LSB_LTXBIAS_WARN_REG   0x17"

.SS "#define SFP_LSB_LTXPWR_ALARM_REG   0x1B"

.SS "#define SFP_LSB_LTXPWR_WARN_REG   0xF"

.SS "#define SFP_LSB_LVCC_ALARM_REG   0xB"

.SS "#define SFP_LSB_LVCC_WARN_REG   0xF"

.SS "#define SFP_LSB_RXPWR_REG   0x69"

.SS "#define SFP_LSB_TEMP_REG   0x61"

.SS "#define SFP_LSB_TXBIAS_REG   0x65"

.SS "#define SFP_LSB_TXPWR_REG   0x67"

.SS "#define SFP_LSB_VCC_REG   0x63"

.SS "#define SFP_MSB_HRXPWR_ALARM_REG   0x20"

.SS "#define SFP_MSB_HRXPWR_WARN_REG   0x24"

.SS "#define SFP_MSB_HTEMP_ALARM_REG   0x0"

.SS "#define SFP_MSB_HTEMP_WARN_REG   0x4"

.SS "#define SFP_MSB_HTXBIAS_ALARM_REG   0x10"

.SS "#define SFP_MSB_HTXBIAS_WARN_REG   0x14"

.SS "#define SFP_MSB_HTXPWR_ALARM_REG   0x18"

.SS "#define SFP_MSB_HTXPWR_WARN_REG   0xC"

.SS "#define SFP_MSB_HVCC_ALARM_REG   0x8"

.SS "#define SFP_MSB_HVCC_WARN_REG   0xC"

.SS "#define SFP_MSB_LRXPWR_ALARM_REG   0x22"

.SS "#define SFP_MSB_LRXPWR_WARN_REG   0x26"

.SS "#define SFP_MSB_LTEMP_ALARM_REG   0x2"

.SS "#define SFP_MSB_LTEMP_WARN_REG   0x6"

.SS "#define SFP_MSB_LTXBIAS_ALARM_REG   0x12"

.SS "#define SFP_MSB_LTXBIAS_WARN_REG   0x16"

.SS "#define SFP_MSB_LTXPWR_ALARM_REG   0x1A"

.SS "#define SFP_MSB_LTXPWR_WARN_REG   0xE"

.SS "#define SFP_MSB_LVCC_ALARM_REG   0xA"

.SS "#define SFP_MSB_LVCC_WARN_REG   0xE"

.SS "#define SFP_MSB_RXPWR_REG   0x68"

.SS "#define SFP_MSB_TEMP_REG   0x60"

.SS "#define SFP_MSB_TXBIAS_REG   0x64"

.SS "#define SFP_MSB_TXPWR_REG   0x66"

.SS "#define SFP_MSB_VCC_REG   0x62"

.SS "#define SFP_PHYS_DEV   0x0"

.SS "#define SFP_STAT_REG   0x6E"

.SH "Variable Documentation"
.PP 
.SS "char* ams_channels[]"
\fBInitial value:\fP.PP
.nf
= {
        "PS LPD Temperature",
        "PS FPD Temperature",
        "VCC PS LPD voltage",
        "VCC PS FPD voltage",
        "PS Aux voltage reference",
        "DDR I/O VCC voltage",
        "PS IO Bank 503 voltage",
        "PS IO Bank 500 voltage",
        "VCCO_PSIO1 voltage",
        "VCCO_PSIO2 voltage",
        "VCC_PS_GTR voltage",
        "VTT_PS_GTR voltage",
        "VCC_PSADC voltage",
        "PL Temperature",
        "PL Internal voltage",
        "PL Auxiliary voltage",
        "ADC Reference P+ voltage",
        "ADC Reference N\- voltage",
        "PL Block RAM voltage",
        "LPD Internal voltage",
        "FPD Internal voltage",
        "PS Auxiliary voltage",
        "PL VCCADC voltage"
    }
.fi

.SS "int break_flag = 0"

.SS "int dig0_backup_flag = 1"

.SS "int dig0_main_flag = 1"

.SS "int dig1_backup_flag = 1"

.SS "int dig1_main_flag = 1"

.SS "int eth0_flag = 1"

.SS "int eth1_flag = 1"

.SS "int GPIO_BASE_ADDRESS = 0"

.SS "int sfp0_connected = 0"

.SS "int sfp1_connected = 0"

.SS "int sfp2_connected = 0"

.SS "int sfp3_connected = 0"

.SS "int sfp4_connected = 0"

.SS "int sfp5_connected = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
