.TH "DPB_I2cSensors" 3 "Version 1.0.0" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DPB_I2cSensors
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_pcb_temp\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp0_2_volt\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp3_5_volt\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_som_volt\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp0_A0\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp1_A0\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp2_A0\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp3_A0\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp4_A0\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp5_A0\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp0_A2\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp1_A2\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp2_A2\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp3_A2\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp4_A2\fP"
.br
.ti -1c
.RI "struct \fBI2cDevice\fP \fBdev_sfp5_A2\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBI2cDevice\fP dev_pcb_temp"

.SS "struct \fBI2cDevice\fP dev_sfp0_2_volt"

.SS "struct \fBI2cDevice\fP dev_sfp0_A0"

.SS "struct \fBI2cDevice\fP dev_sfp0_A2"

.SS "struct \fBI2cDevice\fP dev_sfp1_A0"

.SS "struct \fBI2cDevice\fP dev_sfp1_A2"

.SS "struct \fBI2cDevice\fP dev_sfp2_A0"

.SS "struct \fBI2cDevice\fP dev_sfp2_A2"

.SS "struct \fBI2cDevice\fP dev_sfp3_5_volt"

.SS "struct \fBI2cDevice\fP dev_sfp3_A0"

.SS "struct \fBI2cDevice\fP dev_sfp3_A2"

.SS "struct \fBI2cDevice\fP dev_sfp4_A0"

.SS "struct \fBI2cDevice\fP dev_sfp4_A2"

.SS "struct \fBI2cDevice\fP dev_sfp5_A0"

.SS "struct \fBI2cDevice\fP dev_sfp5_A2"

.SS "struct \fBI2cDevice\fP dev_som_volt"


.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
