.TH "err" 3 "Version 1.0.1" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
err \- Custom Error Flags
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEINCMD\fP   1"
.br
.RI "Error command not valid\&. "
.ti -1c
.RI "#define \fBERRSET\fP   2"
.br
.RI "Error SET commnad not successful\&. "
.ti -1c
.RI "#define \fBERRREAD\fP   3"
.br
.RI "Error READ command not successful\&. "
.in -1c
.SH "Detailed Description"
.PP 
Shared Memory content 
.SH "Macro Definition Documentation"
.PP 
.SS "#define EINCMD   1"

.PP
Error command not valid\&. 
.SS "#define ERRREAD   3"

.PP
Error READ command not successful\&. 
.SS "#define ERRSET   2"

.PP
Error SET commnad not successful\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
