.TH "I2cDevice" 3 "Version 1.0.0" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2cDevice
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <i2c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "uint16_t \fBaddr\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint16_t addr"
Address of the I2C slave, eg: 0x48 
.SS "int fd"
File descriptor for the I2C bus 
.SS "char* filename"
Path of the I2C bus, eg: /dev/i2c-0 

.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
