.TH "periodic_info" 3 "Version 1.0.0" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
periodic_info
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <timer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsig\fP"
.br
.ti -1c
.RI "sigset_t \fBalarm_sig\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "sigset_t alarm_sig"

.SS "int sig"


.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
