.TH "pth" 3 "Version 1.0.0" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pth \- Child process and threads
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "pid_t \fBchild_pid\fP"
.br
.RI "IIO Event Monitor Process ID\&. "
.ti -1c
.RI "pthread_t \fBt_1\fP"
.br
.RI "AMS alarm Thread\&. "
.ti -1c
.RI "pthread_t \fBt_2\fP"
.br
.RI "I2C alarm Thread\&. "
.ti -1c
.RI "pthread_t \fBt_3\fP"
.br
.RI "Monitoring Thread\&. "
.ti -1c
.RI "pthread_t \fBt_4\fP"
.br
.RI "Command Handling Thread\&. "
.in -1c
.SH "Detailed Description"
.PP 
Threads and subprocesses declaration 
.SH "Variable Documentation"
.PP 
.SS "pid_t child_pid"

.PP
IIO Event Monitor Process ID\&. 
.SS "pthread_t t_1"

.PP
AMS alarm Thread\&. 
.SS "pthread_t t_2"

.PP
I2C alarm Thread\&. 
.SS "pthread_t t_3"

.PP
Monitoring Thread\&. 
.SS "pthread_t t_4"

.PP
Command Handling Thread\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
