.TH "semaph" 3 "Version 1.0.1" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semaph \- Local Semaphores
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "sem_t \fBi2c_sync\fP"
.br
.RI "Semaphore to synchronize I2C Bus usage\&. "
.ti -1c
.RI "sem_t \fBthread_sync\fP"
.br
.RI "Semaphore to synchronize thread creation\&. "
.ti -1c
.RI "sem_t \fBfile_sync\fP"
.br
.RI "Semaphore to synchronize GPIO file accesses\&. "
.ti -1c
.RI "sem_t \fBalarm_sync\fP"
.br
.RI "Semaphore to synchronize GPIO AND Ethernet file accesses\&. "
.ti -1c
.RI "sem_t \fBsem_valid\fP"
.br
.RI "Semaphore to avoid race conditions when JSON validating\&. "
.in -1c
.SH "Detailed Description"
.PP 
Semaphores needed to synchronize the application execution and avoid race conditions 
.SH "Variable Documentation"
.PP 
.SS "sem_t alarm_sync"

.PP
Semaphore to synchronize GPIO AND Ethernet file accesses\&. 
.SS "sem_t file_sync"

.PP
Semaphore to synchronize GPIO file accesses\&. 
.SS "sem_t i2c_sync"

.PP
Semaphore to synchronize I2C Bus usage\&. 
.SS "sem_t sem_valid"

.PP
Semaphore to avoid race conditions when JSON validating\&. 
.SS "sem_t thread_sync"

.PP
Semaphore to synchronize thread creation\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
