.TH "SFP_Masks" 3 "Version 1.0.0" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SFP_Masks \- SFP Alarms Masks
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint16_t \fBalarms_mask\fP [6] = {0,0,0,0,0,0}"
.br
.RI "Alarm mask\&. "
.ti -1c
.RI "uint8_t \fBstatus_mask\fP [6] = {0,0,0,0,0,0}"
.br
.RI "Status mask\&. "
.in -1c
.SH "Detailed Description"
.PP 
SFP Alarms Masks Definitions 
.SH "Variable Documentation"
.PP 
.SS "uint16_t alarms_mask[6] = {0,0,0,0,0,0}"

.PP
Alarm mask\&. 
.SS "uint8_t status_mask[6] = {0,0,0,0,0,0}"

.PP
Status mask\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
