.TH "shm" 3 "Version 1.0.1" "DPB2 App Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shm \- Shared Memory
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBwrapper\fP"
.br
.RI "Shared Memory content\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMEMORY_KEY\fP   7890"
.br
.RI "Shared Memory key\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBmemoryID\fP"
.br
.RI "Shared Memory ID\&. "
.ti -1c
.RI "struct \fBwrapper\fP * \fBmemory\fP"
.br
.RI "Shared Memory segment\&. "
.in -1c
.SH "Detailed Description"
.PP 
Shared Memory content 
.SH "Macro Definition Documentation"
.PP 
.SS "#define MEMORY_KEY   7890"

.PP
Shared Memory key\&. 
.SH "Variable Documentation"
.PP 
.SS "struct \fBwrapper\fP* memory"

.PP
Shared Memory segment\&. 
.SS "int memoryID"

.PP
Shared Memory ID\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DPB2 App Documentation from the source code\&.
